site_name: Modpack Index API Documentation
repo_url: https://github.com/sethryder/modpackindex-api-docs
pages:
- Home: index.md
- API Endpoints:
    - Modpacks: modpacks/modpacks.md
    - Modpack: modpacks/modpack.md
    - Mods: mods/mods.md
    - Mod: mods/mod.md
    - Servers: servers/servers.md
    - Server: servers/server.md